version: "2"

services:
  whaleman:
    image: maxrsb/whaleman:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8090:8090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
